### ISSUE TITLE
Broken netlify link

### ISSUE THREAD

**Issue by Anshu4062** [taruntailor7/boat-lifestyle-clone#8]
The link provided to visit the clone website is broken

**Comment by taruntailor7** [comment]
I will check and update, Thank you for informing me.

**Comment by taruntailor7** [comment]
> The link provided to visit the clone website is broken

It is working for me please check : https://clone-boat-website.netlify.app/

**Comment by Anshu4062** [comment]
Sorry some extension broke it for me in this browser it's fine in other browsers.

**Comment by taruntailor7** [comment]
No worries are you visiting my profile for hiring me or something else
because am looking for change so wanted to know?

**Comment by taruntailor7** [comment]
> No worries are you visiting my profile for hiring me or something else because am looking for change so wanted to know?

No worries are you visiting my profile for hiring me or something else
because am looking for change so wanted to know?

**Comment by taruntailor7** [comment]
> Sorry some extension broke it for me in this browser it's fine in other browsers.

No worries are you visiting my profile for hiring me or something else
because am looking for change so wanted to know?
